[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "pnpm build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "@netlify/plugin-csp-nonce"
    [plugins.inputs]
        reportOnly = false
        reportUri = ""
        unsafeEval = false
