[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "pnpm build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/mads"
    to = "https://madswp.moso.io"
    status = 301
    force = true

[[plugins]]
    package = "@netlify/plugin-csp-nonce"

    [plugins.inputs]
        reportOnly = false
        unsafeEval = true
