// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Divider: typeof import('./components/divider.vue')['default']
    Education: typeof import('./components/education.vue')['default']
    Experience: typeof import('./components/experience.vue')['default']
    MosoFooter: typeof import('./components/mosoFooter.vue')['default']
    MosoHeader: typeof import('./components/mosoHeader.vue')['default']
    Page: typeof import('./components/page.vue')['default']
    Profile: typeof import('./components/profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
